<?php
/**
 * @var \Lcouget\CustomAttribute\Block\Product\View\CustomAttribute $block
 */
$isEnabled = $block->isEnabled();
$customAttribute = $block->getCustomAttribute();
?>

<?php if ($isEnabled && !empty($customAttribute)) : ?>
    <div class="product-custom-attribute-value field name">
        <span class="label"><?=$customAttribute['label'] ?></span>:
        <?= $customAttribute['value'] ?>
    </div>

    <!-- Custom Attribute Validation Form -->
    <div class="product-custom-attribute-input">
        <form id="custom-attribute-form" >
            <fieldset class="fieldset">
                <div class="field name required">
                    <label class="label" for="custom-attribute-field-input"><span>Custom Attribute Validation</span></label>
                    <div class="control">
                        <input name="custom-attribute-field-input" id="custom-attribute-field-input" title="Custom Attribute" value="<?= $customAttribute['value'] ?>" class="input-text" type="text"/>
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" title="Submit" class="action submit primary">
                        <span>Submit</span>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <!-- Custom Attribute Validation Form end-->
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#custom-attribute-form": {
            "validation": {
              "rules": {
                "custom-attribute-field-input": {
                  "required":true,
                  "no-whitespace":true,
                  "alphanumeric":true
                }
              }
            }
        }
    }
</script>
